
#define MIURASDK_LIB_VERSION                     @"1.0.0"

#define MIURASDK_MPI_LOG_FILE_NAME               @"mpi.log"

// NSUserDefault key
#define MIURASDK_USERDEFAULT_PRIORITY_DEVICE_IDENTIFY @"MiuraSDK_priority_device_identify"

// API time out
#define MIURASDK_API_TIMEOUT_COMMON              90.00f

// PED connect retry interval
#define MIURASDK_MPI_CONNECTION_INTERVAL         0.50f

// time-out of execute MPI command.
// 0 is not time-out.
#define MIURASDK_MPI_TIMEOUT_COMMON              60.00f
#define MIURASDK_MPI_TIMEOUT_RECONNECT           120.00f
#define MIURASDK_MPI_TIMEOUT_REBOOT_DEVICE       120.00f
#define MIURASDK_MPI_TIMEOUT_WAIT_DISCONNECT     MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_GET_CONFIGURATION   MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_SELECT_FILE         MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_STREAM_BINARY       MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_READ_BINARY         MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_ARCHIVE_LOG         MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_P2PE_STATUS         MIURASDK_MPI_TIMEOUT_COMMON
#define MIURASDK_MPI_TIMEOUT_P2PE_INITIALIZE     120.00f
#define MIURASDK_MPI_TIMEOUT_P2PE_IMPORT         MIURASDK_MPI_TIMEOUT_COMMON

